"""Production-pilot readiness check for TensorFoundry."""
from __future__ import annotations

import argparse
import json
import os
import shutil
from collections import Counter
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set

from tensorfoundry.distillation.recipe import DISTILLATION_RECIPE_VERSION
from tensorfoundry.evaluation.harness import run_suite
from tensorfoundry.evaluation.regression import (
    RegressionPolicy,
    compare_pilot_readiness,
    load_pilot_readiness_artifact,
    write_regression_reports,
)
from tensorfoundry.export.dataset import export_sft
from tensorfoundry.export.preferences import export_preferences
from tensorfoundry.export.repairs import export_repairs
from tensorfoundry.export.validate import DatasetValidationResult, validate_dataset_jsonl, write_dataset_manifest
from tensorfoundry.learning.curriculum import export_curriculum
from tensorfoundry.logging.validate import validate_jsonl_file
from tensorfoundry.models.registry import ProviderCheck, check_provider_for_model
from tensorfoundry.training.readiness import (
    TrainingDatasetCheck,
    build_training_preflight,
    check_optional_training_dependencies,
    write_training_preflight,
)


DEFAULT_SUITE = "src/tensorfoundry/evaluation/benchmarks/v0/suites/decision_v0.json"


def _iter_jsonl_files(root: Path) -> Iterable[Path]:
    return sorted(root.rglob("*.jsonl"))


def _validate_artifacts(logs_dir: Path) -> List[str]:
    issues: List[str] = []
    for path in _iter_jsonl_files(logs_dir):
        for issue in validate_jsonl_file(path):
            issues.append(f"{path}: {issue}")
    return issues


def _reset_generated_outputs(work_dir: Path) -> None:
    """Remove files and directories that are generated by one pilot-check run."""
    for name in ("logs", "results", "datasets", "training"):
        path = work_dir / name
        if path.is_symlink() or path.is_file():
            path.unlink()
        elif path.exists():
            shutil.rmtree(path)
    for name in (
        "pilot_readiness.json",
        "pilot_readiness.md",
        "eval_regression.json",
        "eval_regression.md",
        "training_preflight.json",
        "distillation_recipe.json",
    ):
        path = work_dir / name
        if path.exists() or path.is_symlink():
            path.unlink()


def _provider_checks(
    *,
    require_provider: Set[str],
    hosted_model_id: str,
    local_model_id: str,
) -> List[ProviderCheck]:
    checks: List[ProviderCheck] = [
        check_provider_for_model("dummy_good", required=True),
    ]
    include_hosted = bool(require_provider & {"hosted", "all"})
    include_local = bool(require_provider & {"local", "all"})
    if include_hosted:
        checks.append(check_provider_for_model(hosted_model_id, required=True))
    else:
        optional = check_provider_for_model(hosted_model_id, required=False)
        checks.append(optional)
    if include_local:
        checks.append(check_provider_for_model(local_model_id, required=True))
    else:
        optional = check_provider_for_model(local_model_id, required=False)
        checks.append(optional)
    return checks


def _as_dict(check: ProviderCheck) -> Dict[str, Any]:
    return asdict(check)


def _write_report(payload: Dict[str, Any], report_md: Path) -> None:
    lines = [
        "# TensorFoundry Pilot Readiness",
        "",
        f"- OK: `{str(payload['ok']).lower()}`",
        f"- Work dir: `{payload['work_dir']}`",
        f"- Suites run: `{len(payload['suites'])}`",
        f"- Dataset manifest: `{payload['dataset_manifest']}`",
        "",
        "## Providers",
        "",
        "| provider | model | ok | required | skipped | reason |",
        "|---|---|---:|---:|---:|---|",
    ]
    for c in payload["providers"]:
        lines.append(
            f"| {c['provider']} | `{c['model_id']}` | {str(c['ok']).lower()} | "
            f"{str(c['required']).lower()} | {str(c['skipped']).lower()} | {c.get('reason') or ''} |"
        )
    lines.extend(["", "## Datasets", "", "| kind | rows | ok | path |", "|---|---:|---:|---|"])
    for d in payload["datasets"]:
        lines.append(f"| {d['kind']} | {d['rows']} | {str(d['ok']).lower()} | `{d['path']}` |")
    lines.extend(
        [
            "",
            "## Dataset Quality",
            "",
            "| kind | sha256 | splits | duplicates | provenance | missing refs | quality issues |",
            "|---|---|---|---:|---:|---:|---:|",
        ]
    )
    for d in payload["datasets"]:
        digest = str(d.get("content_sha256") or "")
        split_counts = d.get("split_counts") if isinstance(d.get("split_counts"), dict) else {}
        split_text = ", ".join(f"{k}:{v}" for k, v in sorted(split_counts.items()))
        lines.append(
            f"| {d['kind']} | `{digest[:12]}` | {split_text} | "
            f"{int(d.get('duplicate_count') or 0)} | "
            f"{str(d.get('provenance_checked')).lower()} | "
            f"{len(d.get('missing_artifact_refs') or [])} | "
            f"{len(d.get('quality_issues') or [])} |"
        )
    regression = payload.get("regression")
    if isinstance(regression, dict):
        summary_raw = regression.get("summary")
        summary = summary_raw if isinstance(summary_raw, dict) else {}
        lines.extend(
            [
                "",
                "## Regression Gate",
                "",
                f"- OK: `{str(regression.get('ok')).lower()}`",
                f"- Report: `{regression.get('report_md')}`",
                f"- Pass-rate delta: `{float(summary.get('pass_rate_delta', 0.0)):+.2%}`",
                f"- Mean-score delta: `{float(summary.get('mean_score_delta', 0.0)):+.4f}`",
                f"- Regressed cases: `{int(summary.get('regressed_cases', 0))}`",
                f"- New failing cases: `{int(summary.get('new_failing_cases', 0))}`",
                f"- Worse failure modes: `{int(summary.get('worse_failure_mode_movements', 0))}`",
            ]
        )
    training = payload.get("training_preflight")
    if isinstance(training, dict):
        dataset_rows = training.get("datasets")
        datasets = dataset_rows if isinstance(dataset_rows, list) else []
        lines.extend(
            [
                "",
                "## Training Preflight",
                "",
                f"- OK: `{str(training.get('ok')).lower()}`",
                f"- Base model: `{training.get('base_model')}`",
                f"- Report: `{training.get('report_json')}`",
                f"- Distillation recipe: `{training.get('distillation_recipe') or ''}`",
                "",
                "| role | kind | rows | ok | sha256 | splits |",
                "|---|---|---:|---:|---|---|",
            ]
        )
        for row in datasets:
            if not isinstance(row, dict):
                continue
            digest = str(row.get("content_sha256") or "")
            raw_split_counts = row.get("split_counts")
            split_counts = raw_split_counts if isinstance(raw_split_counts, dict) else {}
            split_text = ", ".join(f"{k}:{v}" for k, v in sorted(split_counts.items()))
            lines.append(
                f"| {row.get('role')} | {row.get('kind')} | {int(row.get('rows') or 0)} | "
                f"{str(row.get('ok')).lower()} | `{digest[:12]}` | {split_text} |"
            )
    failure_modes = _failure_mode_counts(payload["suites"])
    if failure_modes:
        lines.extend(["", "## Failure Modes", "", "| failure_mode | count |", "|---|---:|"])
        for mode, count in failure_modes:
            lines.append(f"| {mode} | {count} |")
    failed_cases = _failed_cases(payload["suites"])
    if failed_cases:
        lines.extend(
            [
                "",
                "## Case Failures",
                "",
                "| suite | model | case | score | failure_mode | trace | reward |",
                "|---|---|---|---:|---|---|---|",
            ]
        )
        for case in failed_cases:
            lines.append(
                f"| {case['suite']} | `{case['model']}` | `{case['case']}` | "
                f"{case['score']:.3f} | {case['failure_mode']} | "
                f"`{case['trace']}` | `{case['reward']}` |"
            )
    if payload["issues"]:
        lines.extend(["", "## Issues", ""])
        lines.extend(f"- {issue}" for issue in payload["issues"])
    report_md.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _failure_mode_counts(suites: List[Dict[str, Any]]) -> List[tuple[str, int]]:
    counts: Counter[str] = Counter()
    for suite in suites:
        for case in suite.get("results", []):
            if not isinstance(case, dict) or bool(case.get("passed")):
                continue
            mode = case.get("failure_mode") or "none"
            counts[str(mode)] += 1
    return counts.most_common()


def _failed_cases(suites: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    cases: List[Dict[str, Any]] = []
    for suite in suites:
        if not isinstance(suite, dict):
            continue
        reward_path = Path(str(suite.get("run_logs_dir", ""))) / "reward.jsonl"
        for case in suite.get("results", []):
            if not isinstance(case, dict) or bool(case.get("passed")):
                continue
            cases.append(
                {
                    "suite": str(suite.get("suite_name", "unknown")),
                    "model": str(suite.get("model_id") or "unknown"),
                    "case": str(case.get("case_id", "unknown")),
                    "score": float(case.get("score") or 0.0),
                    "failure_mode": str(case.get("failure_mode") or "none"),
                    "trace": str(case.get("trace_path") or ""),
                    "reward": str(reward_path),
                }
            )
    return cases


def _training_preflight_summary(preflight: Dict[str, Any]) -> Dict[str, Any]:
    datasets_raw = preflight.get("datasets")
    datasets = datasets_raw if isinstance(datasets_raw, list) else []
    return {
        "version": preflight.get("version"),
        "ok": bool(preflight.get("ok")),
        "report_json": preflight.get("report_json"),
        "base_model": preflight.get("base_model"),
        "quality_gate": bool(preflight.get("quality_gate")),
        "artifact_manifest_version": (
            preflight.get("artifact_manifest", {}).get("version")
            if isinstance(preflight.get("artifact_manifest"), dict)
            else None
        ),
        "datasets": [
            {
                "role": row.get("role"),
                "kind": row.get("kind"),
                "rows": row.get("rows"),
                "ok": row.get("ok"),
                "content_sha256": row.get("content_sha256"),
                "split_counts": row.get("split_counts"),
            }
            for row in datasets
            if isinstance(row, dict)
        ],
        "issues": preflight.get("issues", []),
        "distillation_recipe": preflight.get("distillation_recipe"),
    }


def _write_distillation_recipe(
    *,
    work_dir: Path,
    suite_path: str,
    training_preflight_path: Path,
) -> Path:
    """Write a default evidence-only distillation recipe for the pilot output."""
    out = work_dir / "distillation_recipe.json"
    payload = {
        "version": DISTILLATION_RECIPE_VERSION,
        "id": "pilot-distillation-gate",
        "domain": "pilot",
        "suite": suite_path,
        "baseline_model_id": "dummy_good",
        "candidate_model_id": "dummy_good",
        "training_preflight_path": str(training_preflight_path),
        "thresholds": {
            "max_pass_rate_drop": 0.0,
            "max_mean_score_drop": 0.0,
            "allow_worse_failure_modes": False,
        },
    }
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return out


def run_pilot_check(
    *,
    work_dir: Path,
    suites: List[str],
    require_provider: Set[str],
    hosted_model_id: str,
    local_model_id: str,
    baseline: Optional[Path] = None,
    max_pass_rate_drop: float = 0.0,
    max_mean_score_drop: float = 0.0,
    allow_new_failing_cases: bool = False,
    allow_worse_failure_modes: bool = False,
    training_preflight: bool = False,
    training_base_model: str = "dummy/base",
) -> Dict[str, Any]:
    """Run the offline pilot loop and return a readiness payload."""
    baseline_payload = load_pilot_readiness_artifact(baseline) if baseline is not None else None
    work_dir.mkdir(parents=True, exist_ok=True)
    _reset_generated_outputs(work_dir)
    logs_dir = work_dir / "logs"
    results_dir = work_dir / "results"
    datasets_dir = work_dir / "datasets"

    provider_checks = _provider_checks(
        require_provider=require_provider,
        hosted_model_id=hosted_model_id,
        local_model_id=local_model_id,
    )

    old_model = os.environ.get("TENSORFOUNDRY_MODEL_ID")
    old_provider = os.environ.get("TENSORFOUNDRY_PROVIDER")
    suite_results = []
    try:
        os.environ["TENSORFOUNDRY_PROVIDER"] = "dummy"
        for model_id in ("dummy_good", "dummy_bad"):
            os.environ["TENSORFOUNDRY_MODEL_ID"] = model_id
            for suite in suites:
                result = run_suite(suite_path=suite, output_dir=results_dir, logs_dir=logs_dir)
                suite_results.append(asdict(result))
    finally:
        if old_model is None:
            os.environ.pop("TENSORFOUNDRY_MODEL_ID", None)
        else:
            os.environ["TENSORFOUNDRY_MODEL_ID"] = old_model
        if old_provider is None:
            os.environ.pop("TENSORFOUNDRY_PROVIDER", None)
        else:
            os.environ["TENSORFOUNDRY_PROVIDER"] = old_provider

    issues = _validate_artifacts(logs_dir)

    sft_out = datasets_dir / "pilot.sft.jsonl"
    prefs_out = datasets_dir / "pilot.prefs.jsonl"
    repairs_out = datasets_dir / "pilot.repairs.jsonl"
    curriculum_out = datasets_dir / "pilot.curriculum.jsonl"
    export_sft(
        logs_root=logs_dir,
        out_path=sft_out,
        suite=None,
        min_score=0.7,
        success_only=True,
        limit=None,
        include_prefixes=[],
        exclude_prefixes=[],
        exclude_model_ids=set(),
        step="critic_check",
        use_step_prompt=False,
        min_response_chars=10,
    )
    export_preferences(
        logs_root=logs_dir,
        out_path=prefs_out,
        suite=None,
        min_score=0.0,
        success_only=False,
        include_prefixes=[],
        exclude_prefixes=[],
        exclude_model_ids=set(),
        lambda_cost=0.0,
        mu_latency=0.0,
        max_abs_score_gap=1.0,
        limit=None,
        prompt_normalize="none",
        prompt_source="auto",
        output_format="prefs",
        deterministic=True,
    )
    export_repairs(
        logs_root=logs_dir,
        out_path=repairs_out,
        suite=None,
        min_success_score=0.7,
        max_failure_score=0.8,
        include_prefixes=[],
        exclude_prefixes=[],
        exclude_model_ids=set(),
        limit=None,
        prompt_normalize="none",
        prompt_source="auto",
        output_format="repairs",
    )
    export_curriculum(
        logs_root=logs_dir,
        out_path=curriculum_out,
        suite=None,
        min_score=0.0,
        success_only=False,
        include_prefixes=[],
        exclude_prefixes=[],
        exclude_model_ids=set(),
        step="critic_check",
        use_step_prompt=False,
        min_response_chars=1,
        easy_min_score=0.8,
        escalation_max_score=0.5,
        buckets=None,
        limit=None,
    )

    dataset_results: List[DatasetValidationResult] = [
        validate_dataset_jsonl(
            sft_out,
            kind="sft",
            logs_root=logs_dir,
            require_provenance=True,
            require_splits=True,
            allow_duplicates=False,
            allow_leakage=False,
        ),
        validate_dataset_jsonl(
            prefs_out,
            kind="prefs",
            logs_root=logs_dir,
            require_provenance=True,
            require_splits=True,
            allow_duplicates=False,
            allow_leakage=False,
        ),
        validate_dataset_jsonl(
            repairs_out,
            kind="repairs",
            logs_root=logs_dir,
            require_provenance=True,
            require_splits=True,
            allow_duplicates=False,
            allow_leakage=False,
        ),
        validate_dataset_jsonl(
            curriculum_out,
            kind="curriculum",
            logs_root=logs_dir,
            require_provenance=True,
            require_splits=True,
            allow_duplicates=False,
            allow_leakage=False,
        ),
    ]

    training_preflight_payload = None
    training_preflight_ok = True
    if training_preflight:
        dpo_out = datasets_dir / "pilot.dpo.jsonl"
        export_preferences(
            logs_root=logs_dir,
            out_path=dpo_out,
            suite=None,
            min_score=0.0,
            success_only=False,
            include_prefixes=[],
            exclude_prefixes=[],
            exclude_model_ids=set(),
            lambda_cost=0.0,
            mu_latency=0.0,
            max_abs_score_gap=1.0,
            limit=None,
            prompt_normalize="none",
            prompt_source="auto",
            output_format="dpo",
            deterministic=True,
        )
        dpo_result = validate_dataset_jsonl(
            dpo_out,
            kind="dpo",
            logs_root=logs_dir,
            require_provenance=True,
            require_splits=True,
            allow_duplicates=False,
            allow_leakage=False,
        )
        training_preflight_payload = build_training_preflight(
            base_model=training_base_model,
            dataset_checks=[
                TrainingDatasetCheck(role="sft", path=sft_out, result=dataset_results[0]),
                TrainingDatasetCheck(role="dpo", path=dpo_out, result=dpo_result),
            ],
            outputs={
                "sft_out": str(work_dir / "training" / "sft_lora"),
                "dpo_out": str(work_dir / "training" / "dpo_lora"),
                "sft_dir": str(work_dir / "training" / "sft_lora"),
            },
            quality_gate=True,
            logs_root=str(logs_dir),
            optional_dependencies=check_optional_training_dependencies(),
            smoke_requested=False,
            max_steps=1,
            dry_run=True,
            config={
                "source": "tensorfoundry-pilot-check",
                "training_preflight": True,
                "sft": True,
                "dpo": True,
                "max_steps": 1,
            },
        )
        training_report = write_training_preflight(
            training_preflight_payload,
            work_dir / "training_preflight.json",
        )
        distillation_recipe = _write_distillation_recipe(
            work_dir=work_dir,
            suite_path=suites[0],
            training_preflight_path=training_report,
        )
        training_preflight_ok = bool(training_preflight_payload["ok"])
        if not training_preflight_ok:
            for issue in training_preflight_payload.get("issues", []):
                issues.append(f"training preflight: {issue}")
        training_preflight_payload["report_json"] = str(training_report)
        training_preflight_payload["distillation_recipe"] = str(distillation_recipe)

    manifest_path = write_dataset_manifest(dataset_results, datasets_dir / "manifest.json")
    for dataset_result in dataset_results:
        for issue in dataset_result.issues + dataset_result.quality_issues:
            issues.append(f"dataset {dataset_result.kind}: {issue}")
    provider_ok = all(c.ok or c.skipped for c in provider_checks)
    suites_ok = all(s["failed"] == 0 for s in suite_results)
    datasets_ok = all(r.ok for r in dataset_results)
    readiness_ok = provider_ok and suites_ok and datasets_ok and training_preflight_ok and not issues
    payload: Dict[str, Any] = {
        "version": "pilot_readiness.v0",
        "ok": readiness_ok,
        "work_dir": str(work_dir),
        "logs_dir": str(logs_dir),
        "results_dir": str(results_dir),
        "dataset_manifest": str(manifest_path),
        "providers": [_as_dict(c) for c in provider_checks],
        "suites": suite_results,
        "datasets": [r.to_dict() for r in dataset_results],
        "issues": issues,
    }
    if training_preflight_payload is not None:
        payload["training_preflight"] = _training_preflight_summary(training_preflight_payload)
        payload["distillation_recipe"] = training_preflight_payload.get("distillation_recipe")
    regression_ok = True
    if baseline_payload is not None:
        policy = RegressionPolicy(
            max_pass_rate_drop=max_pass_rate_drop,
            max_mean_score_drop=max_mean_score_drop,
            allow_new_failing_cases=allow_new_failing_cases,
            allow_worse_failure_modes=allow_worse_failure_modes,
        )
        regression_payload = compare_pilot_readiness(
            baseline_payload,
            payload,
            policy=policy,
        )
        regression_reports = write_regression_reports(
            regression_payload,
            json_path=work_dir / "eval_regression.json",
            markdown_path=work_dir / "eval_regression.md",
        )
        regression_ok = bool(regression_payload["ok"])
        deltas = regression_payload["aggregate_deltas"]
        payload["regression"] = {
            "version": regression_payload["version"],
            "ok": regression_ok,
            **regression_reports,
            "summary": {
                "pass_rate_delta": deltas["pass_rate_delta"],
                "mean_score_delta": deltas["mean_score_delta"],
                "changed_cases": len(regression_payload["changed_cases"]),
                "regressed_cases": len(regression_payload["regressed_cases"]),
                "improved_cases": len(regression_payload["improved_cases"]),
                "new_cases": len(regression_payload["new_cases"]),
                "new_failing_cases": len(regression_payload["new_failing_cases"]),
                "missing_cases": len(regression_payload["missing_cases"]),
                "worse_failure_mode_movements": len(
                    regression_payload["worse_failure_mode_movements"]
                ),
            },
            "issues": regression_payload["issues"],
        }
        if regression_payload["issues"]:
            issues.extend(f"regression: {issue}" for issue in regression_payload["issues"])

    payload["ok"] = readiness_ok and regression_ok
    report_json = work_dir / "pilot_readiness.json"
    report_md = work_dir / "pilot_readiness.md"
    report_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    _write_report(payload, report_md)
    payload["report_json"] = str(report_json)
    payload["report_md"] = str(report_md)
    return payload


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Run TensorFoundry production-pilot readiness checks.")
    parser.add_argument("--mode", type=str, default="dummy", choices=["dummy"], help="Pilot mode")
    parser.add_argument("--work-dir", type=str, default="results/pilot_check", help="Output work directory")
    parser.add_argument("--suite", action="append", default=[], help="Suite path; may be repeated")
    parser.add_argument(
        "--require-provider",
        action="append",
        default=[],
        choices=["hosted", "local", "all"],
        help="Fail if the selected provider path is unavailable",
    )
    parser.add_argument(
        "--hosted-model-id",
        type=str,
        default=os.getenv("TENSORFOUNDRY_HOSTED_MODEL_ID", "openai:gpt-5-mini"),
    )
    parser.add_argument(
        "--local-model-id",
        type=str,
        default=os.getenv("TENSORFOUNDRY_LOCAL_MODEL_ID", "ollama:ministral-3:8b"),
    )
    parser.add_argument(
        "--baseline",
        type=str,
        default=None,
        help="pilot_readiness.json file or directory containing one for regression gating",
    )
    parser.add_argument(
        "--max-pass-rate-drop",
        type=float,
        default=0.0,
        help="Allowed aggregate pass-rate drop versus baseline",
    )
    parser.add_argument(
        "--max-mean-score-drop",
        type=float,
        default=0.0,
        help="Allowed aggregate mean-score drop versus baseline",
    )
    parser.add_argument(
        "--allow-new-failing-cases",
        action="store_true",
        help="Do not fail the regression gate for current-only failing cases",
    )
    parser.add_argument(
        "--allow-worse-failure-modes",
        action="store_true",
        help="Do not fail the regression gate for worse failure-mode severity movements",
    )
    parser.add_argument(
        "--training-preflight",
        action="store_true",
        help="Run dry-run training readiness evidence against generated SFT/DPO datasets",
    )
    parser.add_argument(
        "--training-base-model",
        type=str,
        default=os.getenv("TENSORFOUNDRY_TRAINING_BASE_MODEL", "dummy/base"),
        help="Requested base model recorded in optional training preflight evidence",
    )
    args = parser.parse_args(argv)
    payload = run_pilot_check(
        work_dir=Path(args.work_dir),
        suites=args.suite or [DEFAULT_SUITE],
        require_provider=set(args.require_provider),
        hosted_model_id=args.hosted_model_id,
        local_model_id=args.local_model_id,
        baseline=Path(args.baseline) if args.baseline else None,
        max_pass_rate_drop=args.max_pass_rate_drop,
        max_mean_score_drop=args.max_mean_score_drop,
        allow_new_failing_cases=args.allow_new_failing_cases,
        allow_worse_failure_modes=args.allow_worse_failure_modes,
        training_preflight=bool(args.training_preflight),
        training_base_model=args.training_base_model,
    )
    print(f"Pilot readiness: {'OK' if payload['ok'] else 'FAILED'}")
    print(f"Report: {payload['report_md']}")
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
